# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Backend.js CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: cd code/backend/ && npm ci
      - name: Build Project
        # run: cd code/backend/ && npm run build
      - name: Deploy to EC2
        run: |
          scp -r -i "~/.ssh/ec2_rsa" code/backend/ ec2-user@54.159.129.100:~/
          ssh -i "~/.ssh/ec2_rsa" ec2-user@54.159.129.100 'cd code/backend/ && npm start'
