# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Backend CI

on:
  push:
    paths:
      - "code/backend/**"

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      -name: Copy files to deployments/backend and install dependencies
        run: cp -R code/backend /home/ec2-user/deployments
        run: cd /home/ec2-user/deployments/backend && npm ci

      - name: Try starting the smartPoll with PM2
        run: |
          pm2 list | grep smartPoll || pm2 start index.js --name "smartPoll" --watch
        run: pm2 save
