# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend CI

on:
  push:
    paths:
      - "code/web-app/**"

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: copy file for deployement
        run: cp -R code/web-app /home/ec2-user/deployments
      - name: Install dependencies
        run: cd /home/ec2-user/deployments/web-app && npm ci
      - name: Buil next application
        run: cd /home/ec2-user/deployments/web-app && npm run build
      - name: Try starting the app with PM2
        run: cd /home/ec2-user/deployments/web-app && pm2 list | grep next && pm2 restart next || pm2 start npm --name "next" -- start
